development:
  adapter: postgresql
  encoding: unicode
  database: partylist_development
  pool: 5
  username: michaelverdi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: partylist_test
  pool: 5
  username: michaelverdi
  password:
